### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by ahkey** [FabianStammen/ForexFactoryScraper#1]
Hey there, nice work on this. Any idea why my datetimes are like the example below? Looks like the time difference is not being subtracted, but I'm not sure where in the code this is happening. Thanks.

2019-11-01 01:30:00-05:00

**Comment by FabianStammen** [comment]
This is the standard string representation of a timezone-aware datetime object.
The first part(01:30:00) is the time and the second one(-05:00) states the hour difference to UTC. So this time would be 06:30:00 in UTC. This is important as ForexFactory gives the time in EST(-05:00) or EDT(-04:00) depending on the current time.

If you want to process the times further in python you can simply read them with the fromisoformat() method:
`my_datetime = datetime.datetime.fromisoformat(date_string)`

When you want them to be in a different timezone use this for example:
` new_datetime =  my_datetime.astimezone(dateutil.tz.gettz("UTC+1"))`

If you want to represent the correct timezone a location has at the given day specify it like this:
`new_datetime= my_datetime.astimezone(dateutil.tz.gettz("Europe/Berlin"))`

A list of all the timezone names can be found here: [https://en.wikipedia.org/wiki/List_of_tz_database_time_zones](url)

**Comment by ahkey** [comment]
Thank you so much for the detailed explanation! Much appreciated.

**Comment by FabianStammen** [comment]
I also just put out an little update that fixes some other mistake on the timestamps.
I thought the DST on/off value from FunctionForexFactory would affect the times based upon their actual date. Turned out it was just a simple addition of 1 hour and the times are probably saved in UTC.
Now the timezone that the timestamps should be saved in can be given to the scrap method in the main part of the program as a parameter. Default is UTC-5 at the moment as my other dataset from HistData is also saved in this timezone.

**Comment by ahkey** [comment]
This is very useful. Thanks!
